### ISSUE TITLE
zappa STATIC_ROOT configuration

### ISSUE THREAD

**Issue by antat2003** [edgarroman/zappa-django-guide#11]
I am following the how to doc but running into this error:

(zapve) zappashell> zappa manage dev "collectstatic --noinput"
(botocore 1.8.6 (/var/task/zapve/lib/python3.6/site-packages), Requirement.parse('botocore<1.8.0,>=1.7.0'), {'boto3'})
[START] RequestId: eefcf5fe-d720-11e7-ae01-ed6c2ea01425 Version: $LATEST
[DEBUG] 2017-12-02T05:23:30.677Z eefcf5fe-d720-11e7-ae01-ed6c2ea01425 Zappa Event: {'manage': 'collectstatic --noinput'}
You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.: ImproperlyConfigured
Traceback (most recent call last):
  File "/var/task/handler.py", line 509, in lambda_handler
    return LambdaHandler.lambda_handler(event, context)
  File "/var/task/handler.py", line 240, in lambda_handler
    return handler.handler(event, context)
  File "/var/task/handler.py", line 376, in handler
    management.call_command(*event['manage'].split(' '))
  File "/var/task/django/core/management/__init__.py", line 131, in call_command
    return command.execute(*args, **defaults)
  File "/var/task/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/var/task/django/contrib/staticfiles/management/commands/collectstatic.py", line 260, in delete_file
    if self.storage.exists(prefixed_path):
  File "/var/task/django/core/files/storage.py", line 392, in exists
    return os.path.exists(self.path(name))
  File "/var/task/django/contrib/staticfiles/storage.py", line 50, in path
    raise ImproperlyConfigured("You're using the staticfiles app "
django.core.exceptions.ImproperlyConfigured: You're using the staticfiles app without having set the STATIC_ROOT setting to a filesystem path.
[END] RequestId: eefcf5fe-d720-11e7-ae01-ed6c2ea01425
[REPORT] RequestId: eefcf5fe-d720-11e7-ae01-ed6c2ea01425

This is my setting.py

STATIC_URL = '/static/'
STATIC_ROOT =  '/'

# django-storage settings
AWS_STORAGE_BUCKET_NAME = 'zappa-static'

AWS_S3_CUSTOM_DOMAIN = '%s.s3.amazonaws.com' % AWS_STORAGE_BUCKET_NAME

STATIC_URL = "https://%s/" % AWS_S3_CUSTOM_DOMAIN

STATICFILES_STORAGE = 'storages.backends.s3boto.S3BotoStorage'

What does it mean to configure STATIC_ROOT in zappa? and how can i fix this error? 

Cheer.

**Comment by antat2003** [comment]
Turn out, you will need to do zappa update dev then run the collectstatic command. Problem solve. 
Cheer and Beer

**Comment by edgarroman** [comment]
@antat2003 I added some text to help clarify what you ran into
